package gyk4j.wreck.util.logging;

public enum FileEvent {
	DIRECTORY_FOUND,
	FILE_FOUND,
	FILE_ERROR,
	CORRECTIBLE_CREATION,
	CORRECTIBLE_MODIFIED,
	CORRECTIBLE_ACCESSED,
	UNCORRECTIBLE_CREATION,
	UNCORRECTIBLE_MODIFIED,
	UNCORRECTIBLE_ACCESSED
}
